name: Build and Release NikoSpeak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      artifact: nikospeak-win.exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller pillow pygame
      - run: >
          pyinstaller --onefile --windowed --icon=niko.ico --name nikospeak-win
          --add-data "Niko.webp;."
          --add-data "Niko_speak.webp;."
          --add-data "Niko_rare1.png;."
          --add-data "Niko_rare2.png;."
          --add-data "meow1.mp3;."
          --add-data "meow2.mp3;."
          --add-data "meow3.mp3;."
          --add-data "meow4.mp3;."
          --add-data "meow5.mp3;."
          --add-data "rare1.mp3;."
          --add-data "rare2.mp3;."
          --add-data "background.mp3;."
          sprite_switcher.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikospeak-win
          path: dist/nikospeak-win.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller pillow pygame
      - run: |
          pyinstaller --onefile --windowed --name nikospeak-macos \
            --add-data "Niko.webp:." \
            --add-data "Niko_speak.webp:." \
            --add-data "Niko_rare1.png:." \
            --add-data "Niko_rare2.png:." \
            --add-data "meow1.mp3:." \
            --add-data "meow2.mp3:." \
            --add-data "meow3.mp3:." \
            --add-data "meow4.mp3:." \
            --add-data "meow5.mp3:." \
            --add-data "rare1.mp3:." \
            --add-data "rare2.mp3:." \
            --add-data "background.mp3:." \
            sprite_switcher.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikospeak-macos
          path: dist/nikospeak-macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller pillow pygame
      - run: |
          pyinstaller --onefile --name nikospeak-linux \
            --add-data "Niko.webp:." \
            --add-data "Niko_speak.webp:." \
            --add-data "Niko_rare1.png:." \
            --add-data "Niko_rare2.png:." \
            --add-data "meow1.mp3:." \
            --add-data "meow2.mp3:." \
            --add-data "meow3.mp3:." \
            --add-data "meow4.mp3:." \
            --add-data "meow5.mp3:." \
            --add-data "rare1.mp3:." \
            --add-data "rare2.mp3:." \
            --add-data "background.mp3:." \
            sprite_switcher.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikospeak-linux
          path: dist/nikospeak-linux

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nikospeak-win
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: nikospeak-macos
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: nikospeak-linux
          path: .
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nikospeak-win.exe
            nikospeak-macos
            nikospeak-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
