name: Build NikoSpeak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyinstaller pillow pygame
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=niko.ico --name nikospeak ^
            --add-data "Niko.webp;." ^
            --add-data "Niko_speak.webp;." ^
            --add-data "Niko_rare1.png;." ^
            --add-data "Niko_rare2.png;." ^
            --add-data "meow1.mp3;." ^
            --add-data "meow2.mp3;." ^
            --add-data "meow3.mp3;." ^
            --add-data "meow4.mp3;." ^
            --add-data "meow5.mp3;." ^
            --add-data "rare1.mp3;." ^
            --add-data "rare2.mp3;." ^
            --add-data "background.mp3;." ^
            sprite_switcher.py
      - uses: actions/upload-artifact@v4
        with:
          name: nikospeak-win
          path: dist/nikospeak.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyinstaller pillow pygame
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=niko.icns --name nikospeak \
            --add-data "Niko.webp:." \
            --add-data "Niko_speak.webp:." \
            --add-data "Niko_rare1.png:." \
            --add-data "Niko_rare2.png:." \
            --add-data "meow1.mp3:." \
            --add-data "meow2.mp3:." \
            --add-data "meow3.mp3:." \
            --add-data "meow4.mp3:." \
            --add-data "meow5.mp3:." \
            --add-data "rare1.mp3:." \
            --add-data "rare2.mp3:." \
            --add-data "background.mp3:." \
            sprite_switcher.py
      - uses: actions/upload-artifact@v4
        with:
          name: nikospeak-macos
          path: dist/nikospeak

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyinstaller pillow pygame
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name nikospeak \
            --add-data "Niko.webp:." \
            --add-data "Niko_speak.webp:." \
            --add-data "Niko_rare1.png:." \
            --add-data "Niko_rare2.png:." \
            --add-data "meow1.mp3:." \
            --add-data "meow2.mp3:." \
            --add-data "meow3.mp3:." \
            --add-data "meow4.mp3:." \
            --add-data "meow5.mp3:." \
            --add-data "rare1.mp3:." \
            --add-data "rare2.mp3:." \
            --add-data "background.mp3:." \
            sprite_switcher.py
      - uses: actions/upload-artifact@v4
        with:
          name: nikospeak-linux
          path: dist/nikospeak
